# Generated by Django 2.0.4 on 2018-04-14 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=256)),
                ('create_time', models.DateField(default=datetime.datetime.now)),
                ('modify_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=4096)),
                ('create_time', models.DateField(default=datetime.datetime.now)),
                ('modify_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Form_data',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('describe', models.CharField(max_length=1024)),
                ('allow_multiple', models.BooleanField(default=True)),
                ('require', models.BooleanField(default=True)),
                ('create_time', models.DateField(default=datetime.datetime.now)),
                ('modify_time', models.DateField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Question'),
        ),
    ]
