# Generated by Django 2.0.2 on 2018-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_data',
            name='status',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='length',
            field=models.CharField(default='10', max_length=64),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='data',
            field=models.CharField(max_length=16384),
        ),
    ]
