# Generated by Django 2.0.2 on 2018-05-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180502_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
