# Generated by Django 2.0.2 on 2018-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180502_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
